mod about;
mod calendar;
mod dashboard;
mod home;
mod links;
mod login;
mod more;
mod news;
mod reader;
mod settings;
mod weather;

pub use about::AboutPage;
pub use calendar::CalendarPage;
pub use dashboard::Dashboard;
pub use home::HomePage;
pub use links::Links;
pub use login::Login;
pub use more::MorePage;
pub use news::NewsPage;
pub use reader::PostReader;
pub use settings::Settings;
pub use weather::WeatherPage;
