//! Server configuration.
//!
//! Layered with figment: built-in defaults ← TOML file ← `CHAOS_*` env vars.
//! The TOML file is `$CHAOS_CONFIG`, or `./chaos.toml` if present. On NixOS
//! the file will be generated by the future `services.chaos` module from
//! `config.modules.server.servicesList` (see docs/ARCHITECTURE.md).

use std::net::SocketAddr;
use std::path::PathBuf;

use chaos_domain::ServiceDef;
use figment::Figment;
use figment::providers::{Env, Format, Serialized, Toml};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Address the HTTP server binds to.
    pub listen: SocketAddr,
    /// Directory with the built web frontend (trunk dist). When set, the
    /// server serves it with an SPA fallback to index.html.
    pub static_dir: Option<PathBuf>,
    pub monitor: MonitorConfig,
    /// Services shown (and polled) on the dashboard.
    pub services: Vec<ServiceDef>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct MonitorConfig {
    /// Seconds between two polling sweeps.
    pub interval_secs: u64,
    /// Per-request timeout in milliseconds.
    pub timeout_ms: u64,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            listen: "0.0.0.0:4600".parse().expect("valid default listen addr"),
            static_dir: None,
            monitor: MonitorConfig::default(),
            services: Vec::new(),
        }
    }
}

impl Default for MonitorConfig {
    fn default() -> Self {
        Self {
            interval_secs: 60,
            timeout_ms: 5_000,
        }
    }
}

pub fn load() -> anyhow::Result<Config> {
    let config_path = std::env::var("CHAOS_CONFIG").unwrap_or_else(|_| "chaos.toml".into());

    let config = Figment::from(Serialized::defaults(Config::default()))
        .merge(Toml::file(&config_path))
        .merge(Env::prefixed("CHAOS_").split("__"))
        .extract::<Config>()?;
    Ok(config)
}
