//! Server configuration.
//!
//! Layered with figment: built-in defaults ← TOML file ← `CHAOS_*` env vars.
//! The TOML file is `$CHAOS_CONFIG`, or `./chaos.toml` if present. On NixOS
//! the file will be generated by the future `services.chaos` module from
//! `config.modules.server.servicesList` (see docs/ARCHITECTURE.md).

use std::net::SocketAddr;
use std::path::PathBuf;

use chaos_domain::{BookmarkGroup, ColumnSize, ServiceDef, Widget};
use figment::Figment;
use figment::providers::{Env, Format, Serialized, Toml};
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct Config {
    /// Address the HTTP server binds to.
    pub listen: SocketAddr,
    /// Directory with the built web frontend (trunk dist). When set, the
    /// server serves it with an SPA fallback to index.html.
    pub static_dir: Option<PathBuf>,
    /// SQLite database file (created on first start).
    pub db_path: PathBuf,
    /// On-disk cache for proxied service/bookmark icons.
    pub icon_cache_dir: PathBuf,
    /// Search engine template for the dashboard search bar; `{}` is replaced
    /// by the url-encoded query. None hides the search bar.
    pub search_url: Option<String>,
    pub monitor: MonitorConfig,
    pub archive: ArchiveConfig,
    /// Services shown (and polled) on the dashboard.
    pub services: Vec<ServiceDef>,
    /// Static bookmark groups shown on the dashboard.
    pub bookmarks: Vec<BookmarkGroup>,
    /// Dashboard layout: columns of widgets. When empty, a default single
    /// column (search + services + bookmarks) is derived from the fields
    /// above — see `widgets::resolve_layout`.
    pub columns: Vec<ColumnConfig>,
}

/// One dashboard column as written in configuration. Widget instance ids are
/// assigned by the server, so the config only lists widget definitions.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct ColumnConfig {
    pub size: ColumnSize,
    pub widgets: Vec<Widget>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct ArchiveConfig {
    /// Master switch for the archiver worker.
    pub enabled: bool,
    /// Archive new links automatically on save.
    pub auto: bool,
    /// Directory where snapshots are stored (one <link-id>.html per link).
    pub dir: PathBuf,
    /// monolith executable; on NixOS provided via the service PATH.
    pub monolith_bin: String,
    /// Per-page snapshot timeout.
    pub timeout_secs: u64,
}

impl Default for ArchiveConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            auto: true,
            dir: PathBuf::from("archives"),
            monolith_bin: "monolith".into(),
            timeout_secs: 120,
        }
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(default)]
pub struct MonitorConfig {
    /// Seconds between two polling sweeps.
    pub interval_secs: u64,
    /// Per-request timeout in milliseconds.
    pub timeout_ms: u64,
}

impl Default for Config {
    fn default() -> Self {
        Self {
            listen: "0.0.0.0:4600".parse().expect("valid default listen addr"),
            static_dir: None,
            db_path: PathBuf::from("chaos.db"),
            icon_cache_dir: PathBuf::from("icons"),
            search_url: None,
            monitor: MonitorConfig::default(),
            archive: ArchiveConfig::default(),
            services: Vec::new(),
            bookmarks: Vec::new(),
            columns: Vec::new(),
        }
    }
}

impl Default for MonitorConfig {
    fn default() -> Self {
        Self {
            interval_secs: 60,
            timeout_ms: 5_000,
        }
    }
}

pub fn load() -> anyhow::Result<Config> {
    let config_path = std::env::var("CHAOS_CONFIG").unwrap_or_else(|_| "chaos.toml".into());

    let config = Figment::from(Serialized::defaults(Config::default()))
        .merge(Toml::file(&config_path))
        .merge(Env::prefixed("CHAOS_").split("__"))
        .extract::<Config>()?;
    Ok(config)
}
